---
deployment:
  tasks:
    - export DEPLOYPATH=/home/growthrocket/public_html/wp-content/plugins/yhteydenotot/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/templates/myaccount
    - /bin/cp yhteydenotot.php $DEPLOYPATH
    - /bin/cp templates/myaccount/yhteydenotot.php $DEPLOYPATH/templates/myaccount/
